/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.visao;

/**
 *
 * @author Joao
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAluno = new javax.swing.JMenu();
        jMCadastrarAluno = new javax.swing.JMenuItem();
        jMExcluirAluno = new javax.swing.JMenuItem();
        jMAlterarAluno = new javax.swing.JMenuItem();
        jMPesquisar = new javax.swing.JMenuItem();
        jMSair = new javax.swing.JMenuItem();
        jMProfessor = new javax.swing.JMenu();
        jMCadastrarProfessor = new javax.swing.JMenuItem();
        jMExcluirProfessor = new javax.swing.JMenuItem();
        jMAlterarProfessor = new javax.swing.JMenuItem();
        jMPesquisar1 = new javax.swing.JMenuItem();
        jMSair1 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("SCA- Sistema de Cadastro de Aluno");

        jMAluno.setText("Aluno");

        jMCadastrarAluno.setForeground(new java.awt.Color(255, 51, 51));
        jMCadastrarAluno.setText("Cadastrar Aluno");
        jMCadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarAlunoActionPerformed(evt);
            }
        });
        jMAluno.add(jMCadastrarAluno);

        jMExcluirAluno.setForeground(new java.awt.Color(255, 51, 0));
        jMExcluirAluno.setText("Excluir Aluno");
        jMExcluirAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMExcluirAlunoActionPerformed(evt);
            }
        });
        jMAluno.add(jMExcluirAluno);

        jMAlterarAluno.setForeground(new java.awt.Color(255, 51, 0));
        jMAlterarAluno.setText("Alterar Aluno");
        jMAlterarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAlterarAlunoActionPerformed(evt);
            }
        });
        jMAluno.add(jMAlterarAluno);

        jMPesquisar.setText("Pesquisar");
        jMPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPesquisarActionPerformed(evt);
            }
        });
        jMAluno.add(jMPesquisar);

        jMSair.setText("Sair");
        jMSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSairActionPerformed(evt);
            }
        });
        jMAluno.add(jMSair);

        jMenuBar1.add(jMAluno);

        jMProfessor.setText("Professor");

        jMCadastrarProfessor.setForeground(new java.awt.Color(51, 153, 255));
        jMCadastrarProfessor.setText("Cadastrar Professor");
        jMCadastrarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMCadastrarProfessorActionPerformed(evt);
            }
        });
        jMProfessor.add(jMCadastrarProfessor);

        jMExcluirProfessor.setForeground(new java.awt.Color(51, 153, 255));
        jMExcluirProfessor.setText("Excluir Professor");
        jMExcluirProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMExcluirProfessorActionPerformed(evt);
            }
        });
        jMProfessor.add(jMExcluirProfessor);

        jMAlterarProfessor.setForeground(new java.awt.Color(51, 153, 255));
        jMAlterarProfessor.setText("Alterar Professor");
        jMAlterarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAlterarProfessorActionPerformed(evt);
            }
        });
        jMProfessor.add(jMAlterarProfessor);

        jMPesquisar1.setText("Pesquisar");
        jMPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMPesquisar1ActionPerformed(evt);
            }
        });
        jMProfessor.add(jMPesquisar1);

        jMSair1.setText("Sair");
        jMSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSair1ActionPerformed(evt);
            }
        });
        jMProfessor.add(jMSair1);

        jMenuBar1.add(jMProfessor);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addComponent(jLabel1)
                .addContainerGap(256, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addContainerGap(589, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1000, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMCadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarAlunoActionPerformed
        // TODO add your handling code here:
      FormAluno cadaluno = new FormAluno();
        cadaluno.setVisible(true);
    }//GEN-LAST:event_jMCadastrarAlunoActionPerformed

    private void jMExcluirAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMExcluirAlunoActionPerformed
        // TODO add your handling code here:
         FormDeletarAluno delaluno = new FormDeletarAluno();
        delaluno.setVisible(true);
    }//GEN-LAST:event_jMExcluirAlunoActionPerformed

    private void jMPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPesquisarActionPerformed
        // TODO add your handling code here:
        FormPesquisarAluno pesquisar = new FormPesquisarAluno();
        pesquisar.setVisible(true);
    }//GEN-LAST:event_jMPesquisarActionPerformed

    private void jMSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMSairActionPerformed

    private void jMAlterarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAlterarAlunoActionPerformed
        // TODO add your handling code here:
        FormAlterarAluno falt = new FormAlterarAluno();
        falt.setVisible(true);
    }//GEN-LAST:event_jMAlterarAlunoActionPerformed

    private void jMCadastrarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMCadastrarProfessorActionPerformed
        // TODO add your handling code here:
        FormProfessor cadaprofessor = new FormProfessor();
        cadaprofessor.setVisible(true);
    }//GEN-LAST:event_jMCadastrarProfessorActionPerformed

    private void jMExcluirProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMExcluirProfessorActionPerformed
        // TODO add your handling code here:
        FormDeletarProfessor deletaprofessor = new FormDeletarProfessor();
        deletaprofessor.setVisible(true);
    }//GEN-LAST:event_jMExcluirProfessorActionPerformed

    private void jMAlterarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAlterarProfessorActionPerformed
        // TODO add your handling code here:
        FormAlterarProfessor alteraprofessor = new FormAlterarProfessor();
        alteraprofessor.setVisible(true);
    }//GEN-LAST:event_jMAlterarProfessorActionPerformed

    private void jMPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMPesquisar1ActionPerformed
        // TODO add your handling code here:
        FormPesquisarProfessor pesquisaprofessor = new FormPesquisarProfessor();
        pesquisaprofessor.setVisible(true);
    }//GEN-LAST:event_jMPesquisar1ActionPerformed

    private void jMSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSair1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMSair1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMAlterarAluno;
    private javax.swing.JMenuItem jMAlterarProfessor;
    private javax.swing.JMenu jMAluno;
    private javax.swing.JMenuItem jMCadastrarAluno;
    private javax.swing.JMenuItem jMCadastrarProfessor;
    private javax.swing.JMenuItem jMExcluirAluno;
    private javax.swing.JMenuItem jMExcluirProfessor;
    private javax.swing.JMenuItem jMPesquisar;
    private javax.swing.JMenuItem jMPesquisar1;
    private javax.swing.JMenu jMProfessor;
    private javax.swing.JMenuItem jMSair;
    private javax.swing.JMenuItem jMSair1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
